name: Test

on:
  push:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.2']

    name: "Unit tests on ${{ matrix.php }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: zend.assertions=1, error_reporting=-1, display_errors=On
          coverage: none

      - name: Install Composer dependencies
        if: ${{ matrix.php != '8.2' }}
        uses: "ramsey/composer-install@v2"

      - name: Install Composer dependencies (ignore platform)
        if: ${{ matrix.php == '8.2' }}
        uses: "ramsey/composer-install@v2"
        with:
          composer-options: "--ignore-platform-req=php"

      - name: Run tests
        run: vendor/bin/phpunit
