name: Test

on:
  push:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['8.2']
        phpunit: ['9', '10']

    name: "PHP ${{ matrix.php }} with PHPUnit ${{ matrix.phpunit }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: zend.assertions=1, error_reporting=-1, display_errors=On
          tools: phpunit:${{ matrix.phpunit }}
          coverage: none

      - name: Dump autoload
        run: composer du

      - name: Run tests
        run: phpunit
